# Generated by Django 3.2 on 2023-05-01 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, max_length=255)),
                ('twitter_link', models.URLField(blank=True, max_length=255)),
                ('github_link', models.URLField(blank=True, max_length=255)),
                ('avatar', models.ImageField(default='profile_avatars/default_user_avatar.png', upload_to='profile_avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
