# Generated by Django 3.2 on 2023-05-07 17:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_new_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new_avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], default='profile_avatars/default_user_avatar.png', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[315, 315], upload_to='profile_avatars'),
        ),
    ]
