# Generated by Django 3.2 on 2023-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230507_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_avatars/default_user_avatar.png', upload_to='profile_avatars'),
        ),
    ]
