# version: "3.9"
# services:
#   web:
#     depends_on:
#       - postgres
#     build:
#       context: ./StackOverflowClone
#       dockerfile: Dockerfile
#     image: hemal0303/stackclone:pgworking2
#     environment:
#       - PORT=8020
#     env_file:
#       - StackOverflowClone/.env
#     ports:
#       - "8001:8020"
#     command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
#     networks:
#       - mynetwork
#   postgres:
#     image: postgres
#     restart: always
#     env_file:
#       - StackOverflowClone/.env
#     expose:
#       - 5432
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     networks:
#       - mynetwork

#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
#     restart: always
#     container_name: elasticsearch
#     environment:
#       - discovery.type=single-node
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
#       - "ELASTIC_PASSWORD=elastic"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     ports:
#       - 9222:9200
#     volumes:
#       - esdata:/usr/share/elasticsearch/data
#     networks:
#       - mynetwork
#   redis:
#     image: redis:7.0.11
#     ports:
#       - "6379:6379"
#     networks:
#       - mynetwork
# volumes:
#   postgres_data:
#   esdata:
#     driver: local

# networks:
#   mynetwork: # Define the network
version: "3.9"

services:
  web:
    image: hemal0303/stackclone:pgworking2
    environment:
      - PORT=8020
    env_file:
      - StackOverflowClone/.env
    ports:
      - "8001:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"  
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - StackOverflowClone/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
