apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: stack-clone-web-prod-env-updated
        env:
          - name: PORT
            value: "9200"
        ports:
        - containerPort: 9200
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200

