apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: stack-clone-elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stack-clone-elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/stack-clone-mynetwork: "true"
        io.kompose.service: stack-clone-elasticsearch
    spec:
      containers:
        - env:
            - name: ELASTIC_PASSWORD
              value: elastic
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
          image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
          name: elasticsearch
          ports:
            - containerPort: 9200
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: esdata
      restartPolicy: Always
      volumes:
        - name: esdata
          persistentVolumeClaim:
            claimName: esdata
status: {}
