apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/stack-clone-mynetwork: "true"
        io.kompose.service: postgres
    spec:
      containers:
        - args:
            - -p
            - "5432"
          env:
            - name: CHATGPT_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: CHATGPT_API_KEY
                  name: StackOverflowClone--env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: StackOverflowClone--env
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SUPERUSER_EMAIL
                  name: StackOverflowClone--env
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SUPERUSER_PASSWORD
                  name: StackOverflowClone--env
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SUPERUSER_USERNAME
                  name: StackOverflowClone--env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: StackOverflowClone--env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: StackOverflowClone--env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: StackOverflowClone--env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: StackOverflowClone--env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: StackOverflowClone--env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: StackOverflowClone--env
            - name: SOCIAL_AUTH_GITHUB_KEY
              valueFrom:
                configMapKeyRef:
                  key: SOCIAL_AUTH_GITHUB_KEY
                  name: StackOverflowClone--env
            - name: SOCIAL_AUTH_GITHUB_SECRET
              valueFrom:
                configMapKeyRef:
                  key: SOCIAL_AUTH_GITHUB_SECRET
                  name: StackOverflowClone--env
            - name: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
              valueFrom:
                configMapKeyRef:
                  key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
                  name: StackOverflowClone--env
            - name: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
              valueFrom:
                configMapKeyRef:
                  key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
                  name: StackOverflowClone--env
          image: postgres
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
status: {}
