apiVersion: apps/v1
kind: Deployment
metadata:
  name: stack-clone-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stack-clone-postgres
  template:
    metadata:
      labels:
        app: stack-clone-postgres
    spec:
      containers:
        - name: stack-clone-postgres
          image: postgres
          envFrom:
          - secretRef:
              name: stack-clone-web-prod-env-updated
          ports:
            - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: stack-clone-postgres-service
spec:
  selector:
    app: stack-clone-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
