# Generated by Django 4.1.7 on 2023-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="vote", name="answer",),
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.CharField(
                choices=[("up", "Up"), ("down", "Down")], max_length=20
            ),
        ),
    ]
