# Generated by Django 3.2 on 2023-09-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
