# Generated by Django 3.2 on 2023-09-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_notification_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='description',
            field=models.CharField(blank=True, default='No description available at the moment.', max_length=250, null=True),
        ),
    ]
